/** Allowed colors. */
type RangeColor =
    'AliceBlue' |
    'AntiqueWhite' |
    'Aqua' |
    'Aquamarine' |
    'Azure' |
    'Beige' |
    'Bisque' |
    'Black' |
    'BlanchedAlmond' |
    'Blue' |
    'BlueViolet' |
    'Brown' |
    'BurlyWood' |
    'CadetBlue' |
    'Chartreuse' |
    'Chocolate' |
    'Coral' |
    'CornflowerBlue' |
    'Cornsilk' |
    'Crimson' |
    'Cyan' |
    'DarkBlue' |
    'DarkCyan' |
    'DarkGoldenRod' |
    'DarkGrey' |
    'DarkGreen' |
    'DarkKhaki' |
    'DarkMagenta' |
    'DarkOliveGreen' |
    'Darkorange' |
    'DarkOrchid' |
    'DarkRed' |
    'DarkSalmon' |
    'DarkSeaGreen' |
    'DarkSlateBlue' |
    'DarkSlateGrey' |
    'DarkTurquoise' |
    'DarkViolet' |
    'DeepPink' |
    'DeepSkyBlue' |
    'DimGray' |
    'DodgerBlue' |
    'FireBrick' |
    'FloralWhite' |
    'ForestGreen' |
    'Fuchsia' |
    'Gainsboro' |
    'GhostWhite' |
    'Gold' |
    'GoldenRod' |
    'Grey' |
    'Green' |
    'GreenYellow' |
    'HoneyDew' |
    'HotPink' |
    'IndianRed' |
    'Indigo' |
    'Ivory' |
    'Khaki' |
    'Lavender' |
    'LavenderBlush' |
    'LawnGreen' |
    'LemonChiffon' |
    'LightBlue' |
    'LightCoral' |
    'LightCyan' |
    'LightGoldenRodYellow' |
    'LightGrey' |
    'LightGreen' |
    'LightPink' |
    'LightSalmon' |
    'LightSeaGreen' |
    'LightSkyBlue' |
    'LightSlateGrey' |
    'LightSteelBlue' |
    'LightYellow' |
    'Lime' |
    'LimeGreen' |
    'Linen' |
    'Magenta' |
    'Maroon' |
    'MediumAquaMarine' |
    'MediumBlue' |
    'MediumOrchid' |
    'MediumPurple' |
    'MediumSeaGreen' |
    'MediumSlateBlue' |
    'MediumSpringGreen' |
    'MediumTurquoise' |
    'MediumVioletRed' |
    'MidnightBlue' |
    'MintCream' |
    'MistyRose' |
    'Moccasin' |
    'NavajoWhite' |
    'Navy' |
    'OldLace' |
    'Olive' |
    'OliveDrab' |
    'Orange' |
    'OrangeRed' |
    'Orchid' |
    'PaleGoldenRod' |
    'PaleGreen' |
    'PaleTurquoise' |
    'PaleVioletRed' |
    'PapayaWhip' |
    'PeachPuff' |
    'Peru' |
    'Pink' |
    'Plum' |
    'PowderBlue' |
    'Purple' |
    'Red' |
    'RosyBrown' |
    'RoyalBlue' |
    'SaddleBrown' |
    'Salmon' |
    'SandyBrown' |
    'SeaGreen' |
    'SeaShell' |
    'Sienna' |
    'Silver' |
    'SkyBlue' |
    'SlateBlue' |
    'SlateGrey' |
    'Snow' |
    'SpringGreen' |
    'SteelBlue' |
    'Tan' |
    'Teal' |
    'Thistle' |
    'Tomato' |
    'Turquoise' |
    'Violet' |
    'Wheat' |
    'White' |
    'WhiteSmoke' |
    'Yellow' |
    'YellowGreen';

interface SliderProps {
    /** Minimum value that can be set on the slider. */
    defaultMinValue: number;
    /** Maximum value that can be set on the slider. */
    defaultMaxValue: number;
    /** Color of the selected slice of the slider. Default to 'Green'. */
    color?: RangeColor;
    /** Indicates if minimum/maximum values labels should be shown. Default to `false`. */
    showLabels?: boolean;
    /** Step to change slider value. Default to 1. */
    step?: number;
}

export type { RangeColor, SliderProps }
